import { afterEach, beforeEach, expect, test, vi } from 'vitest'

beforeEach(() => vi.resetModules())
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers() })

test('预览资产同时提供 SSH 与 SFTP 连接入口所需的协议', async () => {
  const { previewBackend } = await import('./previewBackend')
  const detail = await previewBackend.getAsset({ profile: 'production', organization: 'org-dev', asset: '7f3c91bd' })
  expect(detail.protocols).toContainEqual({ name: 'sftp', port: 22 })
})

test('预览 SFTP 会话独立于 SSH，目录候选不可用时回到 home', async () => {
  const { previewBackend } = await import('./previewBackend')
  const request = { profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' }
  const first = await previewBackend.startSFTPSession({ ...request, directory: '/missing' })
  const second = await previewBackend.startSFTPSession(request)
  expect(first.directory).toBe('/home/deploy')
  expect(second.id).not.toBe(first.id)
  const directory = await previewBackend.readSFTPDirectory(first.id, first.directory)
  expect(directory.entries.some((entry) => entry.name === 'projects')).toBe(true)
  await previewBackend.closeSFTPSession(first.id)
  expect((await previewBackend.listSFTPSessions()).find((session) => session.id === second.id)?.status).toBe('active')
})

test('预览支持创建、重命名和删除目录并刷新文件列表', async () => {
  const { previewBackend: backend } = await import('./previewBackend')
  const session = await backend.startSFTPSession({ profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' })
  await backend.makeSFTPDirectory(session.id, '/home/deploy/new')
  await backend.renameSFTPEntry(session.id, '/home/deploy/new', 'renamed')
  expect((await backend.readSFTPDirectory(session.id, '/home/deploy')).entries.map((item) => item.name)).toContain('renamed')
  expect((await backend.readSFTPDirectory(session.id, '/home/deploy/renamed')).entries).toEqual([])
  await backend.removeSFTPEntries(session.id, ['/home/deploy/renamed'])
  expect((await backend.readSFTPDirectory(session.id, '/home/deploy')).entries.map((item) => item.name)).not.toContain('renamed')
})

test('预览文件选择器返回示例路径，上传队列推进后更新远程目录', async () => {
  vi.useFakeTimers()
  const { previewBackend: backend } = await import('./previewBackend')
  const session = await backend.startSFTPSession({ profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' })
  const files = await backend.chooseSFTPUploadFiles()
  expect(files).toEqual(['/preview/uploads/notes.txt', '/preview/uploads/release.zip'])
  expect(await backend.chooseSFTPUploadDirectory()).toBe('/preview/uploads/release')
  expect(await backend.chooseSFTPDownloadDirectory()).toBe('/preview/downloads')
  const states: string[] = []
  const unsubscribe = backend.onSFTPTransfer((transfer) => states.push(transfer.status))
  const queued = await backend.startSFTPTransfer({ sessionId: session.id, direction: 'upload', sources: [files[1]], destination: session.directory })
  expect(queued[0].status).toBe('queued')
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.listSFTPTransfers(session.id))[0]).toMatchObject({ status: 'completed', transferred: 640_000, total: 640_000 })
  expect((await backend.readSFTPDirectory(session.id, session.directory)).entries).toContainEqual(expect.objectContaining({ name: 'release.zip', size: 640_000 }))
  expect(states).toContain('running')
  expect(states).toContain('completed')
  unsubscribe()
})

test('预览同名冲突保留两者时生成新名称并保留原文件', async () => {
  vi.useFakeTimers()
  const { previewBackend: backend } = await import('./previewBackend')
  const session = await backend.startSFTPSession({ profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' })
  const [transfer] = await backend.startSFTPTransfer({ sessionId: session.id, direction: 'upload', sources: ['/preview/uploads/notes.txt'], destination: session.directory })
  await vi.advanceTimersByTimeAsync(200)
  expect((await backend.listSFTPTransfers(session.id))[0]).toMatchObject({ status: 'conflict', conflict: { destination: '/home/deploy/notes.txt' } })
  await backend.resolveSFTPConflict(transfer.id, 'keep-both', false)
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.readSFTPDirectory(session.id, session.directory)).entries.map((entry) => entry.name)).toEqual(expect.arrayContaining(['notes.txt', 'notes (1).txt']))
  expect((await backend.listSFTPTransfers(session.id))[0].status).toBe('completed')
})

test('预览冲突决策可应用到整批并清理已结束任务', async () => {
  vi.useFakeTimers()
  const { previewBackend: backend } = await import('./previewBackend')
  const session = await backend.startSFTPSession({ profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' })
  const [first] = await backend.startSFTPTransfer({ sessionId: session.id, direction: 'upload', sources: ['/preview/uploads/notes.txt', '/preview/uploads/notes.txt'], destination: session.directory })
  await vi.advanceTimersByTimeAsync(200)
  await backend.resolveSFTPConflict(first.id, 'skip', true)
  expect((await backend.listSFTPTransfers(session.id)).map((entry) => entry.status)).toEqual(['skipped', 'skipped'])
  await backend.clearCompletedSFTPTransfers(session.id)
  expect(await backend.listSFTPTransfers(session.id)).toEqual([])
})

test('预览取消任务停止进度，重试从头完成', async () => {
  vi.useFakeTimers()
  const { previewBackend: backend } = await import('./previewBackend')
  const session = await backend.startSFTPSession({ profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' })
  const [transfer] = await backend.startSFTPTransfer({ sessionId: session.id, direction: 'upload', sources: ['/preview/uploads/release.zip'], destination: session.directory })
  await vi.advanceTimersByTimeAsync(500)
  await backend.cancelSFTPTransfer(transfer.id)
  const [cancelled] = await backend.listSFTPTransfers(session.id)
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.listSFTPTransfers(session.id))[0]).toMatchObject({ status: 'cancelled', transferred: cancelled.transferred })
  expect(await backend.retrySFTPTransfer(transfer.id)).toMatchObject({ status: 'queued', transferred: 0 })
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.listSFTPTransfers(session.id))[0].status).toBe('completed')
})

test('预览文件夹上传下载保留内容，失败任务保留原因并允许重试', async () => {
  vi.useFakeTimers()
  const { previewBackend: backend } = await import('./previewBackend')
  const session = await backend.startSFTPSession({ profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' })
  await backend.startSFTPTransfer({ sessionId: session.id, direction: 'upload', sources: ['/preview/uploads/release'], destination: session.directory })
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.readSFTPDirectory(session.id, '/home/deploy/release')).entries.map((entry) => entry.name)).toContain('README.md')
  const [download] = await backend.startSFTPTransfer({ sessionId: session.id, direction: 'download', sources: ['/home/deploy/future'], destination: '/preview/downloads' })
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.listSFTPTransfers(session.id)).find((entry) => entry.id === download.id)).toMatchObject({ status: 'failed', error: expect.any(String) })
  await backend.makeSFTPDirectory(session.id, '/home/deploy/future')
  await backend.retrySFTPTransfer(download.id)
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.listSFTPTransfers(session.id)).find((entry) => entry.id === download.id)?.status).toBe('completed')
})

test('预览覆盖在完成后替换内容，关闭会话只取消自己的传输', async () => {
  vi.useFakeTimers()
  const { previewBackend: backend } = await import('./previewBackend')
  const request = { profile: 'production', organization: 'org-dev', target: '7f3c91bd', account: 'account-deploy' }
  const first = await backend.startSFTPSession(request)
  const second = await backend.startSFTPSession(request)
  const [overwrite] = await backend.startSFTPTransfer({ sessionId: first.id, direction: 'upload', sources: ['/preview/uploads/notes.txt'], destination: first.directory })
  await vi.advanceTimersByTimeAsync(200)
  await backend.resolveSFTPConflict(overwrite.id, 'overwrite', false)
  expect((await backend.readSFTPDirectory(first.id, first.directory)).entries.find((entry) => entry.name === 'notes.txt')?.size).toBe(1200)
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.readSFTPDirectory(first.id, first.directory)).entries.find((entry) => entry.name === 'notes.txt')?.size).toBe(2000)
  await backend.startSFTPTransfer({ sessionId: first.id, direction: 'upload', sources: ['/preview/uploads/release.zip'], destination: first.directory })
  await backend.startSFTPTransfer({ sessionId: second.id, direction: 'upload', sources: ['/preview/uploads/release'], destination: second.directory })
  await backend.closeSFTPSession(first.id)
  expect((await backend.listSFTPTransfers(first.id))[1].status).toBe('cancelled')
  await vi.advanceTimersByTimeAsync(2_000)
  expect((await backend.listSFTPTransfers(second.id))[0].status).toBe('completed')
})
